# Base configs
baseurl: "http://photography.portertech.ca"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Sean Porter"
subtitle: "Capturing moments."
author: "Sean Porter"
bio: "Hi."
publicise: "Something."
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/portertech"
  github: "https://www.github.com/portertech"
  
