# Base configs
baseurl: "http://photography.portertech.ca"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Sean Porter"
subtitle: "Capturing moments."
author: "Sean Porter"
bio: "I am a photography enthusiast living in Williams Lake, BC, Canada. While I experiment in all genres of photography, my passion is outdoor sports action and landscapes."
publicise: "I am in search of local opportunities to improve my craft and create stunning images."
social_urls:
  twitter: "https://www.twitter.com/portertech"
